# Interactive script to create .env.docker file
# This script prompts for SQL Server Docker configuration values

Write-Host "SQL Server Docker Environment Setup" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

# Function to validate password strength
function Test-PasswordStrength {
    param([string]$Password)
    
    if ($Password.Length -lt 8) {
        return $false, "Password must be at least 8 characters long"
    }
    
    if ($Password -notmatch '[A-Z]') {
        return $false, "Password must contain at least one uppercase letter"
    }
    
    if ($Password -notmatch '[a-z]') {
        return $false, "Password must contain at least one lowercase letter"
    }
    
    if ($Password -notmatch '[0-9]') {
        return $false, "Password must contain at least one number"
    }
    
    if ($Password -notmatch '[^A-Za-z0-9]') {
        return $false, "Password must contain at least one special character"
    }
    
    return $true, "Password is valid"
}

# Prompt for SA Password
$saPassword = ""
$passwordValid = $false
while (-not $passwordValid) {
    $saPassword = Read-Host "Enter SQL Server SA password (required, min 8 chars, must include uppercase, lowercase, number, and special char)"
    
    if ([string]::IsNullOrWhiteSpace($saPassword)) {
        Write-Host "Password cannot be empty. Please try again." -ForegroundColor Red
        continue
    }
    
    $isValid, $message = Test-PasswordStrength -Password $saPassword
    if ($isValid) {
        $passwordValid = $true
        Write-Host "Password is valid." -ForegroundColor Green
    } else {
        Write-Host "Password validation failed: $message" -ForegroundColor Red
    }
}

# Prompt for Database Name
$defaultDatabase = "talent_finder"
$databasePrompt = "Enter database name"
Write-Host "$databasePrompt [$defaultDatabase]: " -NoNewline -ForegroundColor Yellow
$database = Read-Host
if ([string]::IsNullOrWhiteSpace($database)) {
    $database = $defaultDatabase
}
Write-Host "Using database name: $database" -ForegroundColor Green

# Prompt for Port
$defaultPort = "1433"
$portPrompt = "Enter SQL Server port"
Write-Host "$portPrompt [$defaultPort]: " -NoNewline -ForegroundColor Yellow
$port = Read-Host
if ([string]::IsNullOrWhiteSpace($port)) {
    $port = $defaultPort
} else {
    # Validate port is a number
    $portNum = 0
    if (-not [int]::TryParse($port, [ref]$portNum) -or $portNum -lt 1 -or $portNum -gt 65535) {
        Write-Host "Invalid port number. Using default: $defaultPort" -ForegroundColor Yellow
        $port = $defaultPort
    }
}
Write-Host "Using port: $port" -ForegroundColor Green

# Create .env.docker file
$envContent = @"
# SQL Server Docker Configuration
# Generated by setup-env-docker.ps1

# SQL Server SA (System Administrator) password
MSSQL_SA_PASSWORD=$saPassword

# Database name
MSSQL_DATABASE=$database

# Port mapping for SQL Server
MSSQL_PORT=$port
"@

$envFilePath = Join-Path (Join-Path $PSScriptRoot "..") ".env.docker" | Resolve-Path -ErrorAction SilentlyContinue
if (-not $envFilePath) {
    $envFilePath = Join-Path (Get-Location) ".env.docker"
}

$envContent | Out-File -FilePath $envFilePath -Encoding utf8 -NoNewline

Write-Host ""
Write-Host "Successfully created .env.docker file at: $envFilePath" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Start SQL Server: .\scripts\start-sql-server.ps1" -ForegroundColor Yellow
Write-Host "2. Import BACPAC: .\scripts\import-bacpac.ps1" -ForegroundColor Yellow
